name: sg_benchmark
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - argcomplete=1.12.3
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.0.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - click=8.0.3
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cython=0.29.24
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - einops=0.3.2
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.2.1
  - hdf5=1.10.6
  - icu=58.2
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=7.0.1
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nltk=3.6.5
  - notebook=6.4.5
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.2
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycocotools=2.0.2
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.7.0
  - pytz=2021.3
  - pyzmq=22.2.1
  - qt=5.9.7
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - regex=2021.8.3
  - scipy=1.6.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - timm=0.4.12
  - tk=8.6.11
  - torchaudio=0.7.0
  - torchvision=0.8.0
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typing_extensions=3.10.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - cityscapesscripts==2.2.0
    - coloredlogs==15.0.1
    - humanfriendly==10.0
    - kiwisolver==1.3.2
    - ninja==1.10.2.2
    - opencv-python==4.5.4.58
    - pillow==8.4.0
    - pyquaternion==0.9.9
    - pyyaml==6.0
    - typing==3.7.4.3
    - yacs==0.1.8

